language: ruby
rvm:
  - 2.5.0
  - jruby

node_js:
  - "node"

install:
  # - gem uninstall bundler
  # - gem install bundler --version '1.7.4'
  - bundle install
  - nvm install 14.2

before_script:
  - npm install

script:
  # - bundle exec rubocop
  # - npm test
# - npm run lint
